IONIS.SW/IONIS.SW.WebApp/Models/ErrorViewModel.cs
using System;

namespace IONIS.SW.WebApp.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

IONIS.SW/IONIS.SW.WebApp/Models/IdeaModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Models
{
    public class IdeaModel
    {
        public int IdeaId { get; set; }

        public string Wording { get; set; }

        public int PersonId { get; set; }
        public int MeetingId { get; set; }

        public DateTime CreationDate { get; set; }
    }
}

IONIS.SW/IONIS.SW.WebApp/Models/MeetingModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Models
{
    public class MeetingModel
    {
        public int MeetingId { get; set; }

        public string Title { get; set; }
        public string Description { get; set; }


        public DateTime CreationDate { get; set; }

        public DateTime HoldingDate { get; set; }

        public int Statut { get; set; }

        public int PersonId { get; set; }
    }
}

IONIS.SW/IONIS.SW.WebApp/Models/OpinionModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Models
{
    public class OpinionModel
    {
        public int OpinionId { get; set; }

        public string Type { get; set; }

        public int PersonId { get; set; }
        public int IdeaId { get; set; }
    }
}

IONIS.SW/IONIS.SW.WebApp/Models/ParticipateModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Models
{
    public class ParticipateModel
    {
        public int ParticipateId { get; set; }
        public int PersonCreatorId { get; set; }
        public int PersonCreateId { get; set; }
        public int MeetingId { get; set; }
    }
}

IONIS.SW/IONIS.SW.WebApp/Models/PersonModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Models
{
    public class PersonModel
    {
        public int PersonId { get; set; }

        public string FirstName { get; set; }

        public string LastName { get; set; }

        public string Mail { get; set; }

        public string Password { get; set; }

        public string Profil { get; set; }
    }
}

IONIS.SW/IONIS.SW.WebApp/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using IONIS.SW.WebApp.Models;

namespace IONIS.SW.WebApp.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult About()
        {
            ViewData["Message"] = "Your application description page.";

            return View();
        }

        public IActionResult Contact()
        {
            ViewData["Message"] = "Your contact page.";

            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

IONIS.SW/IONIS.SW.WebApp/Controllers/MeetingController.cs
using IONIS.SW.DAL;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace IONIS.SW.WebApp.Controllers
{
    //[Route("Meeting")]
    public class MeetingController : Controller
    {
        readonly MeetingGateway _meetingGateway;

        public MeetingController(MeetingGateway meetingGateway)
        {
            _meetingGateway = meetingGateway;
        }
        [HttpPost]
        public async Task<IActionResult> Create(string title, string description, DateTime creationDate, DateTime holdingDate, int personId)
        {
            var res = await _meetingGateway.CreateMeeting(title, description, creationDate, holdingDate, personId);
            return View();
        }
    }
}

IONIS.SW/IONIS.SW.WebApp/Views/Home/About.cshtml
@{
    ViewData["Title"] = "About";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<p>Use this area to provide additional information.</p>

IONIS.SW/IONIS.SW.WebApp/Views/Home/Contact.cshtml
@{
    ViewData["Title"] = "Contact";
}
<h2>@ViewData["Title"]</h2>
<h3>@ViewData["Message"]</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong> <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

IONIS.SW/IONIS.SW.WebApp/Views/Home/Index.cshtml
@model IONIS.SW.WebApp.Models.MeetingModel

@{
    ViewData["Title"] = "Home Page";
}

<h2>View</h2>

<h4>MeetingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingId" class="control-label"></label>
                <input asp-for="MeetingId" class="form-control" />
                <span asp-validation-for="MeetingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoldingDate" class="control-label"></label>
                <input asp-for="HoldingDate" class="form-control" />
                <span asp-validation-for="HoldingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Statut" class="control-label"></label>
                <input asp-for="Statut" class="form-control" />
                <span asp-validation-for="Statut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IONIS.SW/IONIS.SW.WebApp/Views/Meeting/Index.cshtml
@using IONIS.SW.WebApp.Models
@model MeetingModel

<form method="post" asp-controller="Meeting" asp-action="Create">
    <label>Titre</label>
    <input asp-for="Title" />

    <label>Description</label>
    <input asp-for="Description" />

    <label>Date de Creation</label>
    <input asp-for="CreationDate" />

    <label>Date de la reunion</label>
    <input asp-for="HoldingDate" />

    <button type="submit">Valider</button>
</form>

IONIS.SW/IONIS.SW.WebApp/Views/Meeting/View.cshtml
@model IONIS.SW.WebApp.Models.MeetingModel

@{
    ViewData["Title"] = "View";
}

<h2>View</h2>

<h4>MeetingModel</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="View">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="MeetingId" class="control-label"></label>
                <input asp-for="MeetingId" class="form-control" />
                <span asp-validation-for="MeetingId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Title" class="control-label"></label>
                <input asp-for="Title" class="form-control" />
                <span asp-validation-for="Title" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Description" class="control-label"></label>
                <input asp-for="Description" class="form-control" />
                <span asp-validation-for="Description" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="CreationDate" class="control-label"></label>
                <input asp-for="CreationDate" class="form-control" />
                <span asp-validation-for="CreationDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="HoldingDate" class="control-label"></label>
                <input asp-for="HoldingDate" class="form-control" />
                <span asp-validation-for="HoldingDate" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Statut" class="control-label"></label>
                <input asp-for="Statut" class="form-control" />
                <span asp-validation-for="Statut" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="PersonId" class="control-label"></label>
                <input asp-for="PersonId" class="form-control" />
                <span asp-validation-for="PersonId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

IONIS.SW/IONIS.SW.WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - IONIS.SW.WebApp</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
        <link rel="stylesheet" href="~/css/site.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute" />
        <link rel="stylesheet" href="~/css/site.min.css" asp-append-version="true" />
    </environment>
</head>
<body>
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a asp-area="" asp-controller="Home" asp-action="Index" class="navbar-brand">IONIS.SW.WebApp</a>
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li><a asp-area="" asp-controller="Home" asp-action="Index">Home</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="About">About</a></li>
                    <li><a asp-area="" asp-controller="Home" asp-action="Contact">Contact</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <partial name="_CookieConsentPartial" />

    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; 2019 - IONIS.SW.WebApp</p>
        </footer>
    </div>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.js"></script>
        <script src="~/js/site.js" asp-append-version="true"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://ajax.aspnetcdn.com/ajax/jquery/jquery-3.3.1.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha384-tsQFqpEReu7ZLhBV2VZlAu7zcOV+rXbYlF2cqB8txI/8aZajjp4Bqd+V6D5IgvKT">
        </script>
        <script src="https://ajax.aspnetcdn.com/ajax/bootstrap/3.3.7/bootstrap.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa">
        </script>
        <script src="~/js/site.min.js" asp-append-version="true"></script>
    </environment>

    @RenderSection("Scripts", required: false)
</body>
</html>